services:
  postgres:
    image: postgres:16-alpine
    container_name: match-postgres
    environment:
        - POSTGRES_USER=MatchMicroservice
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=MatchDB
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL","pg_isready -U MatchMicroservice -d MatchDB"]
        interval: 10s
        timeout: 5s
        retries: 5
  
volumes:
  pgdata: