name: Feature
description: Request a new feature
title: "[Feature]: "
labels: ["type:feature"]

body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature

  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: Conditions for completion

  - type: textarea
    attributes:
      label: Tasks
      description: Implementation steps
